language: java

jdk:
  - openjdk9

os:
  - linux`

before_script:
  - rvm install jruby-9.2.6
  - rvm use jruby
  - ./exe/jbundle install

script:
  - ./gradlew check
  - ./exe/jrake
  - ./exe/cucumber

